title: Github pages with Jekyll
author: wuchichou
email: wuchichou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the page for the purpose of practising building a GitHub pages with Jekyll

# social links
twitter_username: wuchichou
github_username: wuchichou

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
